# Generated by Django 4.1.7 on 2023-02-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_remove_restaurant_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_hours',
        ),
    ]
