# Generated by Django 4.1.7 on 2023-02-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_hours',
            field=models.JSONField(default=None),
        ),
    ]
