# Generated by Django 4.1.7 on 2023-02-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_delivery_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_hours',
            field=models.JSONField(null=True),
        ),
    ]
